import { AdminController } from "./controllers/admin-controller.js";
import { StaffAdminController } from "./controllers/staff-admin-controller.js";
import { SalonRepository } from "./repositories/salon-repository.js";
import { UserRepository } from "./repositories/user-repository.js";
import { VerificationRepository } from "./repositories/verification-repository.js";
import { AdminService } from "./services/admin-service.js";
import { AuthService } from "./services/auth-service.js";
import { StaffAdminService } from "./services/staff-admin-service.js";
import { StaffAuthService } from "./services/staff-auth-service.js";
import { StaffPortalService } from "./services/staff-portal-service.js";
export const userRepository = new UserRepository();
const salonRepository = new SalonRepository();
const verificationRepository = new VerificationRepository();
export const authService = new AuthService(userRepository);
export const adminService = new AdminService(userRepository, salonRepository);
export const staffAuthService = new StaffAuthService();
export const staffAdminService = new StaffAdminService(userRepository, verificationRepository);
export const staffPortalService = new StaffPortalService(userRepository, verificationRepository, staffAuthService);
export const adminController = new AdminController(authService, adminService);
export const staffAdminController = new StaffAdminController(authService, staffAdminService);
